version: "3.7"

services:

    # NODEOS SETUP
    nodeos:
        env_file:
            .env
        container_name: "${COMPOSE_PROJECT_NAME}_nodeos"
        image: "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}"
        command: "/opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=${COMPOSE_PROJECT_NAME}_nodeos:8888 --http-alias=127.0.0.1:${NODEOS_API_PORT} --http-alias=localhost:${NODEOS_API_PORT}"
        hostname: "${COMPOSE_PROJECT_NAME}_nodeos"
        ports:
            - "${NODEOS_API_PORT}:${NODEOS_API_PORT}/tcp"
            - "${NODEOS_PORT}:${NODEOS_PORT}/tcp"
        expose:
            - "${NODEOS_API_PORT}"
        volumes:
            - ~/$NODEOS_VOLUME_NAME:/opt/eosio/bin/data-dir
        cap_add:
            - IPC_LOCK
        stop_grace_period: 10m
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${NODEOS_API_PORT}"]
            test: ["CMD", "curl", "-f", "http://localhost:$NODEOS_PORT"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # KEOSD SETUP
    keosd:
        env_file:
            .env
        container_name: "${COMPOSE_PROJECT_NAME}_keosd"
        image: "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}"
        command: "/opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:${KEOSD_API_PORT} --http-alias=${COMPOSE_PROJECT_NAME}_keosd:${KEOSD_API_PORT} --http-alias=localhost:${KEOSD_API_PORT}"
        hostname: "${COMPOSE_PROJECT_NAME}_keosd"
        links:
            - nodeos
        ports:
            - "${KEOSD_API_PORT}:${KEOSD_API_PORT}/tcp"
        volumes:
            - ~/$KEOSD_VOLUME_NAME:/opt/eosio/bin/data-dir
        stop_grace_period: 10m
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${KEOSD_API_PORT}"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
